### ISSUE TITLE
generated template.yml doesn't work with `sam local start-api`

### ISSUE THREAD

**Issue by theburningmonk** [SAPessi/serverless-sam#14] opened 2017-12-19 00:46 UTC
Using the same `serverless.yml` as #12, when I run `sam local start-api` I get the error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1702c38]

goroutine 1 [running]:
main.start(0xc42008d040)
        /root/go/src/github.com/awslabs/aws-sam-local/start.go:122 +0xe18
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.HandleAction(0x17d56e0, 0x19d02a0, 0xc42008d040, 0xc4202d3e00, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a5845, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19cde2e, 0x3c9, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:207 +0xb72
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4204e6340, 0xc42008ca00, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.startApp(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:293 +0x8a3
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:93 +0x14c7
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).Run(0xc420491d40, 0xc42000e2d0, 0x3, 0x3, 0x0,0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()
        /root/go/src/github.com/awslabs/aws-sam-local/main.go:375 +0x24a2
```

I'm using SAM version `0.2.4`.

The only way I have found to "fix it" is to remove both the `BigMouth` CFN resource, as well as all references to it in the template.yml. I appreciate this is probably problem with SAM local, but I'm just wondering if you have any insight into what might be the problem.

**Comment by sapessi** [comment] 2017-12-19 16:28
hey @theburningmonk, let me investigate. I can help push a fix to SAM local if the issue is there.

Looks like it could be related to awslabs/aws-sam-local#225

**Comment by theburningmonk** [comment] 2017-12-19 16:33
Yes, it's the same project - building a demo app as part of [AWS Lambda in Motion](http://bit.ly/aws-lambda-in-motion), in one of the modules I demonstrate how to run & debug functions locally using the Serverless framework & SAM local

**Comment by sapessi** [comment] 2017-12-19 20:46
I've submitted a [pull request](https://github.com/awslabs/aws-sam-local/pull/233) to fix the issue in SAM local. I'll let you know once it's merged and published.

**Comment by theburningmonk** [comment] 2017-12-19 20:57
@SAPessi awesome, thank you so much 👍

**Comment by sapessi** [comment] 2018-01-22 18:25
The issue was merged. Closing this.

**Closed as completed by sapessi** 2018-01-22 18:25 UTC
